Class {
	#name : 'FEBDesperateSaverStrategy',
	#superclass : 'FEBStrategy',
	#category : 'FE_Beta-Model',
	#package : 'FE_Beta-Model'
}

{ #category : 'testing' }
FEBDesperateSaverStrategy >> isDesperateSaver [

	^ true
]

{ #category : 'as yet unclassified' }
FEBDesperateSaverStrategy >> moneyThreshold [

	^ 0.2
]

{ #category : 'as yet unclassified' }
FEBDesperateSaverStrategy >> shapeOfPov [

	^ #circle
]

{ #category : 'as yet unclassified' }
FEBDesperateSaverStrategy >> timeThreshold [

	^ 0.2
]
