Class {
	#name : 'FEBRichBastardStrategy',
	#superclass : 'FEBStrategy',
	#category : 'FE_Beta-Model',
	#package : 'FE_Beta-Model'
}

{ #category : 'testing' }
FEBRichBastardStrategy >> isRichBastard [

	^ true
]

{ #category : 'as yet unclassified' }
FEBRichBastardStrategy >> moneyThreshold [

	^ 0.6
]

{ #category : 'as yet unclassified' }
FEBRichBastardStrategy >> shapeOfPov [ 

	^ #star
]

{ #category : 'as yet unclassified' }
FEBRichBastardStrategy >> timeThreshold [

	^ 0.6
]
